### ISSUE TITLE
Release new version to fix >8.1 notices

### ISSUE THREAD

**Issue by PatrickHuiskens** [viafintech/Barzahlen-PHP#27]
Hi,

Currently we have a working dev-master. Would it be possible to release a new version with these fixes compared to 2.1.2?

**Comment by martinseener** [comment]
Hi @PatrickHuiskens,

give me a day or two. I will check this and try to release the new version soon.

**Comment by martinseener** [comment]
Closing this as v2.2.0 with the PHP8 support has been released.

**Comment by PatrickHuiskens** [comment]
Hi, sorry never checked this.

It was already in your branch but not released. Thanks!
